import { Lato, Roboto } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import Navbar from "@/components/navbar/Navbar";

const lato = Lato({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-lato",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "GroceryScout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} overflow-y-scroll scrollbar-hide bg-gray-50`}
      >
        <Navbar />
        <main className="max-w-6xl mx-auto px-12 py-4 ">{children}</main>
      </body>
    </html>
  );
}
